### ISSUE TITLE
Suggestion: use .f90 extension

### ISSUE THREAD

**Issue by rouson** [wimvanderbauwhede/RefactorF4Acc#11]
As a matter of style, I recommend using the `.f90` file extension instead of `.f95`. See this [Dr. Fortran blog post] for details.

[Dr. Fortran blog post]: https://software.intel.com/en-us/blogs/2013/01/11/doctor-fortran-in-source-form-just-wants-to-be-free

**Comment by wimvanderbauwhede** [comment]
I changed the default to .f90, it is configurable anyway.
