### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by rouson** [wimvanderbauwhede/RefactorF4Acc#3]
Is there a way to run the test suite automatically?  I tried the following:
```
$ ./NIST_F78_test_suite/fcvs21_f95/Test_rf4a/run_testsuite.pl
cp: ../FM001.f: No such file or directory
TEST CASE FM001.f
refactorF4acc.pl -c rf4a_fm001.cfg  -g fm001
The EQUIVALENCE  statement is not supported, please rewrite your code (or ignore at your peril):
SOURCE: ./NIST_F78_test_suite/fcvs21_f95/FM500.f LINE #34
CODE UNIT: an502
LINE: 'equivalence (ay3s, dz3s)   
...                  
```
and there were hundreds more lines with similar messages.

**Comment by wimvanderbauwhede** [comment]
The way to run the NIST test suite is explained in the README.md under "To run the NIST test suite", and there is a single script to run it. In short:

$ cd tests/NIST_F78_test_suite/fcvs21_f95/Test_rf4a
$ ./generate_and_run.sh

Please ensure that the environment varianble `$FC` is set to the Fortran compiler you want to use. The above is a summary, the README.md has full details.

**Comment by wimvanderbauwhede** [comment]
About those "The EQUIVALENCE  statement is not supported" messages, my compiler does not attempt to refactor these statements, but they can break referential transparency, so I felt I had to warn the user. Similar for some other features that I have no intention of supporting. In most cases, the resulting code is just fine.
