### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by rouson** [wimvanderbauwhede/RefactorF4Acc#4]
For third parties wishing to contribute to this project, please document your guidelines, including how to

1) Contribute to the software 
2) Report issues or problems with the software
3) Seek support

**Comment by wimvanderbauwhede** [comment]
OK, will do. I'll make a CONTRIBUTE file. Although this is not really a requirement of Open Source Software, isn't it. And it is very unlikely that anyone else would wish to contribute.

**Comment by labarba** [comment]
Contributing guidelines are required by JOSS, and listed in the [Review Criteria](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by wimvanderbauwhede** [comment]
No worries, I will ad them :-)

**Comment by wimvanderbauwhede** [comment]
I've added a CONTRIBUTE.md file, based on another project from the JOSS site.
