### ISSUE TITLE
Broken links on the wiki

### ISSUE THREAD

**Issue by rouson** [wimvanderbauwhede/RefactorF4Acc#9]
Broken links:
- [ ] On the [Home] page: [Slides of my talk about Refactor4FAcc at AOGS-2012](
https://github.com/wimvanderbauwhede/RefactorF4Acc/blob/master/slides_RefactorF4Acc.pdf?raw=true)
- [ ] On the [Overview] page: [PDF]

[Home]: 
https://github.com/wimvanderbauwhede/RefactorF4Acc/wiki
[Slides of my talk about Refactor4FAcc at AOGS-2012]: https://github.com/wimvanderbauwhede/RefactorF4Acc/blob/master/slides_RefactorF4Acc.pdf?raw=true
[Overview]: https://github.com/wimvanderbauwhede/RefactorF4Acc/wiki/Overview
[PDF]: https://github.com/wimvanderbauwhede/RefactorF4Acc/blob/master/slides_RefactorF4Acc.pdf?raw=true

**Comment by wimvanderbauwhede** [comment]
I have fixed these and added links to two presentations.
